EyeSeeTea/data-management-app

src/components/steps/org-units/OrgUnitsStep.tsx

* **Issue:** Closes #38
* **d2-ui-components**:
- Remove filters by Level  & by Groups

Remove org unit filters #38

---

src/components/steps/sectors/SectorsStep.tsx

Show search bar for locations

---

package.json
src/components/org-units/UserOrgUnits.tsx
yarn.lock

* **Issue:** Closes #
* **project-monitoring-metadata**: Requires #
* **d2-api**: Requires #
* **d2-ui-components**: Requires #
-
-

Use new prop for OrgUnitsSelector to allow fixing a width

---

cypress/integration/project-list.spec.js
i18n/en.pot
src/components/dropdown/MultipleDropdown.tsx
src/models/Config.ts
src/models/Project.ts
src/models/ProjectDb.ts
src/models/__tests__/Config.spec.ts
src/models/__tests__/Project.spec.ts
src/models/__tests__/config.json
src/pages/projects-list/ProjectsList.tsx
src/pages/projects-list/ProjectsListFilters.tsx

* **Issue:** Closes #120
- Sector filter not done for now
- SearchBox width not changed for now (the new filters fit). We'll revist on another task.

Projects list filters 

---

src/models/user.ts

Data Reviewer can create projects

Fix: Data Reviewer can create projects

---

.travis.yml
babel.config.js
package.json
yarn.lock

- Update cypress to 4.2.0
- Fix app posting (the culprit: `cd d2-docker`, this changed the directory and the zip was not found)

Feature/update cypress 4.2

---

package.json
src/components/steps/data-elements/DataElementsTable.tsx
yarn.lock

* **Issue:** Required by https://github.com/EyeSeeTea/d2-ui-components/pull/148

Use new ObjectsTable prop rowConfig for unselectable rows

---

.travis.yml
cypress/integration/05.project-download.spec.js
package.json
src/components/steps/sharing/SharingStep.tsx
src/models/Project.ts
src/models/ProjectSharing.ts
src/models/ProjectsList.ts
src/models/__tests__/Project.spec.ts
src/pages/projects-list/ProjectsList.tsx
yarn.lock

* **Issue:** Closes #232
* **d2-ui-components**: https://github.com/EyeSeeTea/d2-ui-components/pull/166

Customize Sharing step

---

src/pages/dashboard/Dashboard.tsx

Sometimes the dashboard would render empty, fix it.

Fix intermitent Dashboard iframe load error (never set height 0)

---

src/components/steps/data-elements/DataElementsTable.tsx

* **Issue:** Applies https://github.com/EyeSeeTea/d2-ui-components/pull/165

Use new paginationOptions prop in ObjectsTable

---

src/components/steps/disaggregation/DisaggregationStep.tsx
src/models/ProjectDb.ts

Fixes problem with closed data value on data entry.

Set start of day for dataInputPeriod now

---

cypress/integration/00.project-create.spec.js
src/components/steps/sharing/SharingStep.tsx
src/models/ProjectSharing.ts
src/models/__tests__/ProjectDb.spec.ts

* **Issue:** Closes #269
Note that automatic sharing is only applied to new projects, so the existing ones will not get the current user sharing even if edited and re-saved. Also, if someone edits another user's project, they won't be added to the project.

Add current user to sharing of new projects

---

.travis.yml
cypress/integration/00.project-create.spec.js
cypress/integration/07.project-edit.spec.js
src/pages/project-wizard/ProjectWizard.tsx

Swap wizard steps Disaggregation and MER selection

---

.travis.yml
package.json
src/models/ProjectSharing.ts
src/models/ProjectsList.ts
src/models/__tests__/Project.spec.ts

* **Issue:** Closes #276
- Get `orgUnit->actual-dataSet->access` and check metadata (read/write) and data (read/write) access.
- Note that viewer users shouldn't need so much permission, but the permissions on the sharing step are all or nothing.

Narrow down project list checking dataset permissions

---

i18n/en.pot
src/models/MerReport.ts
src/models/__tests__/mer-data.ts
src/pages/report/MerReport.tsx

* **Issue:** Closes #323, #322, #324 
- Added fulll location name to the lexycographical order of MER data (all ASC). Now:  `[locations.length, locations.join(), project.name, project.id, dataElement.name]`.

MER tweaks/fixes

---

i18n/en.pot
package.json
src/components/app/App.tsx
src/components/org-units/UserOrgUnits.tsx
src/components/utils/errors.ts
src/index.js
src/index.ts
src/models/Config.ts
src/models/MerReport.ts
src/models/__tests__/Project.spec.ts
src/pages/report/MerReport.tsx
yarn.lock

* **Issue:** Closes #336
* Uses https://github.com/EyeSeeTea/d2-api/pull/61
- Convert index.js to TS.

MER refinements

---

cypress/integration/00.project-create.spec.js
i18n/en.pot
src/components/steps/general-info/GeneralInfoStep.tsx
src/models/Project.ts
src/models/ProjectDb.ts
src/models/__tests__/Project.spec.ts
src/pages/projects-list/ProjectsList.tsx
src/utils/string.ts

* **Issue:** Closes #339, #341

Set filter onlyActive by default + project.subsequentLettering 2/3 chars 

---

i18n/en.pot
src/models/MerReport.ts
src/models/MerReportSpreadsheet.ts
src/models/__tests__/MerReport.spec.ts
src/models/__tests__/mer-data.ts
src/pages/report/DataElementCells.tsx

* **Issue:** Closes https://app.clickup.com/t/cay50y
- Indicators: split in "Indicator code", "Indicator name".
- Use two lines on some headers and more height, it should look better now.
- Column for the interval was not specified. For now, it's called "Dates".
- We cannot use "0.###" as planned without some tinkering (conditional styles or formulas) see https://superuser.com/questions/205759/format-a-number-with-optional-decimal-places-in-excel. Simple solution: use General (default) formatter, which is ok except that we cannot limit to N decimals.
- On React component: Use max 3 decimals for values and 0 decimals for %. Use `/analytics?skipRounding=true`.

[MER] Refactor activities tab [cay50y]

---

README.md
i18n/en.pot
src/components/dropdown/Dropdown.tsx
src/components/dropdown/DropdownForm.tsx
src/models/MerReport.ts
src/models/MerReportSpreadsheet.ts
src/models/__tests__/MerReport.spec.ts
src/models/__tests__/mer-data.ts
src/pages/report/CommentField.tsx
src/pages/report/DataElementCells.tsx
src/pages/report/ReportDataTable.tsx
src/pages/report/ReportTextField.tsx
src/pages/report/TextFieldOnBlur.tsx

* **Issue:** Closes https://app.clickup.com/t/cd0k5y
- We perform another set of requests (we had 2, now 4) to `/analytics` with and without `approvalLevel`.
- Instead of simple number values, data fields now are `{approved: number, all: number}`.
- Added suffix `(CODE)` to indicator name.

[MER] Show approved/total data values [cd0k5y]

---

i18n/en.pot
package.json
src/models/MerReport.ts
src/models/MerReportSpreadsheet.ts
src/models/__tests__/MerReport.spec.ts
src/pages/projects-list/ProjectsList.tsx
src/pages/report/DataElementCells.tsx
src/pages/report/ReportDataTable.tsx
src/pages/report/ReportTextField.tsx
src/pages/report/ReportTextFieldForSector.tsx
src/pages/report/TextFieldOnBlur.tsx
yarn.lock

* **Issue:** Closes
https://app.clickup.com/t/cwvt8d
https://app.clickup.com/t/cww7yf
https://app.clickup.com/t/cwvypm

Visual tweaks

---

src/components/data-entry/DataEntry.tsx
src/components/data-entry/data-entry-hooks.ts
src/components/data-entry/validation-hooks.ts

* **Issue:** Closes #
* **project-monitoring-metadata**: Requires #
* **d2-api**: Requires #
* **d2-ui-components**: Requires #
-
-

Fix data-entry validation on iframe reload

---

package.json
src/models/dataElementsSet.ts

* **Issue:** Closes https://app.clickup.com/t/hf89bj

Use pipe as externals separator

---

.gitignore
src/models/dataElementsSet.ts
src/scripts/get-data-elements-from-instance.ts
src/utils/string.ts

* **Issue:** Closes https://app.clickup.com/t/fb5atq

Get data elements from instance [script]

---

i18n/en.pot
package.json
src/components/steps/data-elements/DataElementsFilters.tsx
src/components/steps/data-elements/table-utils.tsx
src/models/Project.ts
yarn.lock

* **Issue:** Closes:
https://app.clickup.com/t/hq25pr
https://app.clickup.com/t/j32xcz
https://app.clickup.com/t/j32xfh

Replace externals by funders + remove internals option

---

.prettierignore
package.json
src/models/Disaggregation.ts
src/react-app.d.ts
src/scripts/common.ts
src/scripts/covid-datasets.ts
src/scripts/create-all-projects-ou-group.ts
src/scripts/delete-wrong-data-values.ts
yarn.lock

Add infrastructure scripts to fix covid19 disaggregations (dataSets and dataValues)
* **Issue:** Closes:
https://app.clickup.com/t/j98kpa
https://app.clickup.com/t/j94uj7

Add infrastructure scripts to fix covid19 disaggregations

---

package.json
src/models/user.ts

* **Issue:** Closes https://app.clickup.com/t/mx88gu

[Fix] country dashboard access

---

package.json
public/app-config.json
src/components/dashboard/Dashboard.tsx
src/scripts/fix-datasets-disaggregation.ts

- Refactor `openExternalLinksInNewTab` to use `setInterval`

[Dashboard] Fix externals links

---

i18n/en.pot
package.json
src/models/validators/RecurringValidator.ts

* **Issue:** Closes https://app.clickup.com/t/1xpp8b9?comment=780264503

Change message for recurring validator warning message

---

i18n/en.pot
package.json
src/components/dashboard/Dashboard.tsx

* **Issue:** Closes https://app.clickup.com/t/1gbfz66 
Show temporal warning for < 2.36.9 versions

Add warning message for <2.36.8 bug on analytics

---

src/pages/report/ReportDataTable.tsx

* **Issue:** Closes https://app.clickup.com/t/244y3tu

Stick header row for MER report table

---

i18n/en.pot
src/models/Project.ts
src/models/dataElementsSet.ts
src/pages/project-wizard/help-texts.tsx

* **Issue:** Closes https://app.clickup.com/t/244y4qq
- Validate on step change, not on selection/de-selection of MER indicators (feasible, a bit more tricky)
- Tentative snackbar messages.

[MER] Validate max 3 sectors / 3-indicators-per-sector

---

i18n/en.pot
src/components/dashboard/Dashboard.tsx
src/scripts/projects.ts

* **Issue:** Closes https://app.clickup.com/t/1z4fmr1

Remove dashboard warning (fixed in 2.36.11)

---

src/components/steps/general-info/Funders.tsx
src/models/Config.ts

* **Issue:** Closes https://app.clickup.com/t/3d43uj0

use codes instead of shortname for additional designation

---

package.json
src/components/app/App.css
src/components/app/App.tsx
src/components/objects-list/ObjectsList.tsx
src/pages/projects-list/ProjectsListFilters.tsx
src/utils/pagination.ts
yarn.lock

* **Issue:** Closes https://app.clickup.com/t/3dfhb1e
- Use <HeaderBar /> from `@dhis2/ui` instead of `@dhis2/ui-widgets`.
- Tested in mode dev and app.

Use HeaderBar from @dhis2/ui

---

package.json
src/models/ProjectNotification.ts

* **Issue:** Closes https://app.clickup.com/t/3dfg9gc

change data reviewer link to data approval link

---

src/components/data-entry/DataSetStateButton.tsx
src/components/steps/save/SaveStep.tsx
src/models/ProjectNotification.ts

* **Issue:** Closes https://app.clickup.com/t/865bnt2ta
- Create user group with code: `DATA_MANAGEMENT_NOTIFICATION`

Send notifications also to users in notification group

---

package.json
src/models/ProjectNotification.ts

* **Issue:** Closes https://app.clickup.com/t/863gn4btx
- Filter out users checking flag `user.userCredentials.disabled` in ProjectNotification (project save + notifications on data approval)

Exclude disabled users from notifications

---

cypress/integration/00.project-create.spec.js
cypress/integration/01.project-list.spec.js
cypress/integration/07.project-edit.spec.js
cypress/integration/08.project-indicators.spec.js
cypress/integration/09.countries-list.spec.js
cypress/support/pages/indicators-page.js
cypress/support/utils.js
src/components/app/App.css
src/models/Disaggregation.ts
src/models/Project.ts
src/models/ProjectsList.ts
src/pages/project-wizard/ProjectWizard.tsx

* **Issue:** Closes https://app.clickup.com/t/865cqdjy1
- Show disaggregation step only for edit project when this project has at least one COVID19 disaggregation
- Fixed cypress specs to latest changes.

[feature] hide covid step 

---

.eslintrc.js
i18n/en.pot
src/components/steps/save/SaveStep.tsx
src/models/Project.ts
src/models/ProjectInfo.ts
src/models/ProjectNotification.ts
src/models/__tests__/ProjectInfo.spec.ts
src/models/__tests__/__snapshots__/ProjectInfo.spec.ts.snap

* **Issue:** Closes https://app.clickup.com/t/865cqynrb
- Code for SaveStep and notification was reused (in a quick and hack way, with a html->text). I've refactored it to use now proper nodes and two renderers, React for the SaveStep and text for the email.
- Limit dangling data values list on notification to avoid 414 error (body is a query string)

[feature] Improve project save notification

---

cypress/integration/05.project-download.spec.js
src/models/validators/GlobalValidator.ts

* **Issue:** Closes [#](https://app.clickup.com/t/865cqypkn)
- Fix formula 
- Fix linting warnings

[fix] Fix global formula

---

src/models/ProjectsList.ts

* **Issue:** Closes https://app.clickup.com/t/865bfr3vv
- Use projects after the filter by user permissions

[fix ]use projects with user access to build countries dropdown

---

i18n/en.pot
src/components/steps/general-info/GeneralInfoStep.tsx
src/models/Config.ts
src/models/Project.ts
src/models/ProjectDb.ts
src/models/ProjectInfo.ts
src/models/__tests__/Project.spec.ts
src/models/__tests__/ProjectDb.spec.ts
src/models/__tests__/__snapshots__/ProjectInfo.spec.ts.snap
src/models/__tests__/config.json

-   **Issue:** Closes https://app.clickup.com/t/862khy77f
A project is a **"DART project"** if the org. unit is part of the org. unit group **IS_DART_APPLICABLE**
Import metadata using the json file on the clickup issue
**New DART checkbox in create/edit page**
**Showing value at the summary step**

add dart applicable checkbox

---

.github/workflows/main.yml
i18n/en.pot
package.json
src/components/attach-files-dialog/AttachFilesDialog.tsx
src/components/steps/attach-files/AttachFiles.tsx
src/components/steps/attach-files/AttachFilesStep.tsx
src/components/steps/attach-files/DropFiles.tsx
src/models/MerReport.ts
src/models/Project.ts
src/models/ProjectDb.ts
src/models/ProjectDocument.ts
src/models/ProjectDocumentRepository.ts
src/models/ProjectInfo.ts
src/models/__tests__/Project.spec.ts
src/models/__tests__/ProjectDb.spec.ts
src/models/__tests__/__snapshots__/ProjectInfo.spec.ts.snap
src/models/dataElementsSet.ts
src/models/user.ts
src/pages/project-wizard/ProjectWizard.tsx
src/pages/projects-list/ProjectsList.tsx
src/pages/projects-list/ProjectsListConfig.tsx
yarn.lock

* **Issue:** Closes https://app.clickup.com/t/862kjdadb
- Added new step **"Attach Files"**
- Added new contextual action **"Attach files"** on project list.
**New step for create/edit projects**
**Summary**
**Attach Files as a contextual action**
**Edit files from contextual action**

ability to add files to project

---

i18n/en.pot
src/components/attach-files-dialog/AttachFilesDialog.tsx
src/components/steps/attach-files/AttachFiles.tsx
src/components/steps/general-info/GeneralInfoStep.tsx
src/models/Project.ts
src/models/ProjectDb.ts
src/models/user.ts
src/pages/project-wizard/ProjectWizard.tsx
src/pages/projects-list/ProjectsListConfig.tsx

Improvements and i18n updates

---

.github/workflows/main.yml

- Added `runs-on: self-hosted`

Add self hosted to github actions

---

deploy/auth.template.sh
deploy/clone-pro-to-training.sh
deploy/lib.sh
deploy/push-pro-docker.sh
deploy/start-training-from-pro.sh
deploy/tasks.sh
package.json
yarn.lock

We have been using them for a while, but not uploaded. It also updates ts-node, something we detected in Boone servers, which has a new v16 node.

Deployment scripts

---

src/models/Config.ts

* **Issue:** Closes https://app.clickup.com/t/869471tx7
- Prefix all user roles used by the app with "DM" (only feedback and admin had it)

Add prefix 'DM' all user roles used in the app with 

---

package.json
src/models/validators/GlobalValidator.ts

* **Issue:** Closes https://app.clickup.com/t/8694fk29a
- Set validateSubIsLessOrEqualThanGlobal as warning, so the save continues.

Set live validation sub/global validation as warning

---

package.json
src/components/utils/use-boolean.ts
src/index.ts
src/pages/data-approval/DataApproval.tsx
src/pages/data-approval/DataApprovalTable.tsx
yarn.lock

* **Issue:** Closes 
Uses approval-app: https://github.com/EyeSeeTea/approval-app/pull/3
- The custom approval app must be installed in the instance.

[Proof of Concept] Use data approval as plugin

---

deploy/clone-pro-to-test.sh
deploy/deploy-test-from-pro.sh
deploy/lib.sh
deploy/push-pro-docker.sh

* **Issue:** https://app.clickup.com/t/1mufv53
- Update docker versions
- Use docker tag instead of d2-docker copy
- Automatic version detection on PRO commit&push

[feature] Update deploy infrastructure

---

src/models/user.ts

* **Issue:** Closes https://app.clickup.com/t/8695fa0pv
#8695fa0pv

allow data reviewers to clone projects

---

src/domain/usecases/GetProjectsByCountryUseCase.ts
src/models/Project.ts
src/pages/country-indicator-report/CountryIndicatorReport.tsx
src/pages/country-indicator-report/IndicatorReportTable.tsx

* **Issue:** Closes https://app.clickup.com/t/8696nt04q

hide reports in unique beneficiaries report

---

src/pages/country-indicator-report/CountryIndicatorReport.tsx

* **Issue:** Closes https://app.clickup.com/t/8695qbyrz

order years in unique beneficiaries report
